# Generated by Django 5.1.4 on 2025-01-19 01:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tagalog', models.CharField(max_length=60)),
                ('root', models.CharField(max_length=60)),
                ('accents', models.JSONField()),
                ('alternate_spelling', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('is_irregular_verb', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=60)),
                ('audio_url', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('N', 'noun'), ('V', 'verb'), ('ADJ', 'adjective'), ('ADV', 'adverb'), ('PRON', 'pronoun'), ('PREP', 'preoposition'), ('CONJ', 'conjunction'), ('INTERJ', 'interjection'), ('INTERR', 'interrogative'), ('ART', 'article'), ('PART', 'particle'), ('PRE', 'prefix')], max_length=60)),
                ('english_meanings', models.ManyToManyField(related_name='english_meanings', to='words.english')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_word', models.CharField(max_length=60, unique=True)),
                ('particle', models.CharField(max_length=10)),
                ('english_meaning', models.CharField(max_length=60)),
                ('audio_url', models.CharField(max_length=60)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_words', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagalog', models.CharField(max_length=60, unique=True)),
                ('aspect', models.CharField(choices=[('COMP', 'completed'), ('UNCOMP', 'uncompleted'), ('CONT', 'contemplated')], max_length=10)),
                ('accents', models.JSONField()),
                ('audio_url', models.CharField(max_length=60)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='words.word')),
            ],
        ),
    ]
