# Generated by Django 5.1.4 on 2025-01-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('tagalog', 'accents')},
        ),
    ]
