# Generated by Django 5.1.4 on 2025-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english',
            name='meaning',
            field=models.CharField(max_length=60),
        ),
    ]
